language: node_js
services: postgresql
node_js: "10.20.0"
cache:
  directories:
  - node_modules
env:
  global:
    - PGPORT=5433
    - TEST_DB_NAME=db_test
    - DB_NAME=db_test
    - DB_USER=dbowner
    - DB_PASSWORD=dbpassword
before_script:
  - psql -c 'create database db_test;' -U postgres
install:
  - yarn install
  - yarn add coveralls
script: yarn test
after_success: yarn run coveralls
