sudo: false
language: node_js
services:
  - postgresql
node_js:
  - "10.20.0"
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - yarn install
  - yarn add coveralls
script:
  - yarn test
after_success:
  - yarn run coveralls
